# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro_serving_grpc/tf/tensor_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hydro_serving_grpc.tf import types_pb2 as hydro__serving__grpc_dot_tf_dot_types__pb2
from hydro_serving_grpc.tf import tensor_shape_pb2 as hydro__serving__grpc_dot_tf_dot_tensor__shape__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hydro_serving_grpc/tf/tensor_info.proto',
  package='hydrosphere.tensorflow',
  syntax='proto3',
  serialized_pb=_b('\n\'hydro_serving_grpc/tf/tensor_info.proto\x12\x16hydrosphere.tensorflow\x1a!hydro_serving_grpc/tf/types.proto\x1a(hydro_serving_grpc/tf/tensor_shape.proto\"\x8b\x01\n\nTensorInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x05\x64type\x18\x02 \x01(\x0e\x32 .hydrosphere.tensorflow.DataType\x12>\n\x0ctensor_shape\x18\x03 \x01(\x0b\x32(.hydrosphere.tensorflow.TensorShapeProtoB(\n!io.hydrosphere.serving.tensorflowP\x01\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[hydro__serving__grpc_dot_tf_dot_types__pb2.DESCRIPTOR,hydro__serving__grpc_dot_tf_dot_tensor__shape__pb2.DESCRIPTOR,])




_TENSORINFO = _descriptor.Descriptor(
  name='TensorInfo',
  full_name='hydrosphere.tensorflow.TensorInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hydrosphere.tensorflow.TensorInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='hydrosphere.tensorflow.TensorInfo.dtype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tensor_shape', full_name='hydrosphere.tensorflow.TensorInfo.tensor_shape', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=284,
)

_TENSORINFO.fields_by_name['dtype'].enum_type = hydro__serving__grpc_dot_tf_dot_types__pb2._DATATYPE
_TENSORINFO.fields_by_name['tensor_shape'].message_type = hydro__serving__grpc_dot_tf_dot_tensor__shape__pb2._TENSORSHAPEPROTO
DESCRIPTOR.message_types_by_name['TensorInfo'] = _TENSORINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TensorInfo = _reflection.GeneratedProtocolMessageType('TensorInfo', (_message.Message,), dict(
  DESCRIPTOR = _TENSORINFO,
  __module__ = 'hydro_serving_grpc.tf.tensor_info_pb2'
  # @@protoc_insertion_point(class_scope:hydrosphere.tensorflow.TensorInfo)
  ))
_sym_db.RegisterMessage(TensorInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!io.hydrosphere.serving.tensorflowP\001\370\001\001'))
# @@protoc_insertion_point(module_scope)
