# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro_serving_grpc/contract/model_signature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hydro_serving_grpc.contract import model_field_pb2 as hydro__serving__grpc_dot_contract_dot_model__field__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hydro_serving_grpc/contract/model_signature.proto',
  package='hydrosphere.contract',
  syntax='proto3',
  serialized_pb=_b('\n1hydro_serving_grpc/contract/model_signature.proto\x12\x14hydrosphere.contract\x1a-hydro_serving_grpc/contract/model_field.proto\"\x8d\x01\n\x0eModelSignature\x12\x16\n\x0esignature_name\x18\x01 \x01(\t\x12\x30\n\x06inputs\x18\x02 \x03(\x0b\x32 .hydrosphere.contract.ModelField\x12\x31\n\x07outputs\x18\x03 \x03(\x0b\x32 .hydrosphere.contract.ModelFieldB!\n\x1fio.hydrosphere.serving.contractb\x06proto3')
  ,
  dependencies=[hydro__serving__grpc_dot_contract_dot_model__field__pb2.DESCRIPTOR,])




_MODELSIGNATURE = _descriptor.Descriptor(
  name='ModelSignature',
  full_name='hydrosphere.contract.ModelSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature_name', full_name='hydrosphere.contract.ModelSignature.signature_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='hydrosphere.contract.ModelSignature.inputs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='hydrosphere.contract.ModelSignature.outputs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=264,
)

_MODELSIGNATURE.fields_by_name['inputs'].message_type = hydro__serving__grpc_dot_contract_dot_model__field__pb2._MODELFIELD
_MODELSIGNATURE.fields_by_name['outputs'].message_type = hydro__serving__grpc_dot_contract_dot_model__field__pb2._MODELFIELD
DESCRIPTOR.message_types_by_name['ModelSignature'] = _MODELSIGNATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelSignature = _reflection.GeneratedProtocolMessageType('ModelSignature', (_message.Message,), dict(
  DESCRIPTOR = _MODELSIGNATURE,
  __module__ = 'hydro_serving_grpc.contract.model_signature_pb2'
  # @@protoc_insertion_point(class_scope:hydrosphere.contract.ModelSignature)
  ))
_sym_db.RegisterMessage(ModelSignature)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037io.hydrosphere.serving.contract'))
# @@protoc_insertion_point(module_scope)
