# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro_serving_grpc/contract/model_field.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hydro_serving_grpc.tf import tensor_info_pb2 as hydro__serving__grpc_dot_tf_dot_tensor__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hydro_serving_grpc/contract/model_field.proto',
  package='hydrosphere.contract',
  syntax='proto3',
  serialized_pb=_b('\n-hydro_serving_grpc/contract/model_field.proto\x12\x14hydrosphere.contract\x1a\'hydro_serving_grpc/tf/tensor_info.proto\"\xb2\x02\n\nModelField\x12\x12\n\nfield_name\x18\x01 \x01(\t\x12\x35\n\x04\x64ict\x18\x02 \x01(\x0b\x32%.hydrosphere.contract.ModelField.DictH\x00\x12\x32\n\x04info\x18\x03 \x01(\x0b\x32\".hydrosphere.tensorflow.TensorInfoH\x00\x1a\x94\x01\n\x04\x44ict\x12=\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32/.hydrosphere.contract.ModelField.Dict.DataEntry\x1aM\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .hydrosphere.contract.ModelField:\x02\x38\x01\x42\x0e\n\x0cinfo_or_dictB!\n\x1fio.hydrosphere.serving.contractb\x06proto3')
  ,
  dependencies=[hydro__serving__grpc_dot_tf_dot_tensor__info__pb2.DESCRIPTOR,])




_MODELFIELD_DICT_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='hydrosphere.contract.ModelField.Dict.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='hydrosphere.contract.ModelField.Dict.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='hydrosphere.contract.ModelField.Dict.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=403,
)

_MODELFIELD_DICT = _descriptor.Descriptor(
  name='Dict',
  full_name='hydrosphere.contract.ModelField.Dict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='hydrosphere.contract.ModelField.Dict.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MODELFIELD_DICT_DATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=403,
)

_MODELFIELD = _descriptor.Descriptor(
  name='ModelField',
  full_name='hydrosphere.contract.ModelField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_name', full_name='hydrosphere.contract.ModelField.field_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dict', full_name='hydrosphere.contract.ModelField.dict', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='hydrosphere.contract.ModelField.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MODELFIELD_DICT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='info_or_dict', full_name='hydrosphere.contract.ModelField.info_or_dict',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=113,
  serialized_end=419,
)

_MODELFIELD_DICT_DATAENTRY.fields_by_name['value'].message_type = _MODELFIELD
_MODELFIELD_DICT_DATAENTRY.containing_type = _MODELFIELD_DICT
_MODELFIELD_DICT.fields_by_name['data'].message_type = _MODELFIELD_DICT_DATAENTRY
_MODELFIELD_DICT.containing_type = _MODELFIELD
_MODELFIELD.fields_by_name['dict'].message_type = _MODELFIELD_DICT
_MODELFIELD.fields_by_name['info'].message_type = hydro__serving__grpc_dot_tf_dot_tensor__info__pb2._TENSORINFO
_MODELFIELD.oneofs_by_name['info_or_dict'].fields.append(
  _MODELFIELD.fields_by_name['dict'])
_MODELFIELD.fields_by_name['dict'].containing_oneof = _MODELFIELD.oneofs_by_name['info_or_dict']
_MODELFIELD.oneofs_by_name['info_or_dict'].fields.append(
  _MODELFIELD.fields_by_name['info'])
_MODELFIELD.fields_by_name['info'].containing_oneof = _MODELFIELD.oneofs_by_name['info_or_dict']
DESCRIPTOR.message_types_by_name['ModelField'] = _MODELFIELD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelField = _reflection.GeneratedProtocolMessageType('ModelField', (_message.Message,), dict(

  Dict = _reflection.GeneratedProtocolMessageType('Dict', (_message.Message,), dict(

    DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
      DESCRIPTOR = _MODELFIELD_DICT_DATAENTRY,
      __module__ = 'hydro_serving_grpc.contract.model_field_pb2'
      # @@protoc_insertion_point(class_scope:hydrosphere.contract.ModelField.Dict.DataEntry)
      ))
    ,
    DESCRIPTOR = _MODELFIELD_DICT,
    __module__ = 'hydro_serving_grpc.contract.model_field_pb2'
    # @@protoc_insertion_point(class_scope:hydrosphere.contract.ModelField.Dict)
    ))
  ,
  DESCRIPTOR = _MODELFIELD,
  __module__ = 'hydro_serving_grpc.contract.model_field_pb2'
  # @@protoc_insertion_point(class_scope:hydrosphere.contract.ModelField)
  ))
_sym_db.RegisterMessage(ModelField)
_sym_db.RegisterMessage(ModelField.Dict)
_sym_db.RegisterMessage(ModelField.Dict.DataEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037io.hydrosphere.serving.contract'))
_MODELFIELD_DICT_DATAENTRY.has_options = True
_MODELFIELD_DICT_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
